language: node_js
addons:
  apt:
    packages:
      - festival
      - festvox-kallpc16k
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "9"
  - "8"
os:
  - linux
  - osx
script:
  - npm test
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
